// Types for the modules generated by vite-plugins/blog-content.ts.

declare module "virtual:blog-posts" {
  import type { BlogFrontmatter } from "@/lib/blog/schema";
  import type { BlogHeading } from "@/lib/blog/markdown";

  export type RawBlogPost = Omit<BlogFrontmatter, "updated"> & {
    slug: string;
    updated: string;
    /** Resolved asset URL of the cover image. */
    cover: string;
    /** Cover file name inside src/assets/blog/. */
    coverFile: string;
    coverSize: { width: number; height: number } | null;
    wordCount: number;
    readingMinutes: number;
    headings: BlogHeading[];
  };

  const posts: RawBlogPost[];
  export default posts;
  export const bodies: Record<string, () => Promise<{ default: string }>>;
}

declare module "js-yaml" {
  export const CORE_SCHEMA: unknown;
  export function load(input: string, options?: { schema?: unknown }): unknown;
  const yaml: { CORE_SCHEMA: unknown; load: typeof load };
  export default yaml;
}
