/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComparativaEvisaneRouteImport } from './routes/comparativa.evisane'
import { Route as ComparativaEisiHotelRouteImport } from './routes/comparativa.eisi-hotel'
import { Route as ComparativaAutocontrolpiscinasRouteImport } from './routes/comparativa.autocontrolpiscinas'
import { Route as AdminMensajesRouteImport } from './routes/admin.mensajes'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComparativaEvisaneRoute = ComparativaEvisaneRouteImport.update({
  id: '/comparativa/evisane',
  path: '/comparativa/evisane',
  getParentRoute: () => rootRouteImport,
} as any)
const ComparativaEisiHotelRoute = ComparativaEisiHotelRouteImport.update({
  id: '/comparativa/eisi-hotel',
  path: '/comparativa/eisi-hotel',
  getParentRoute: () => rootRouteImport,
} as any)
const ComparativaAutocontrolpiscinasRoute =
  ComparativaAutocontrolpiscinasRouteImport.update({
    id: '/comparativa/autocontrolpiscinas',
    path: '/comparativa/autocontrolpiscinas',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminMensajesRoute = AdminMensajesRouteImport.update({
  id: '/admin/mensajes',
  path: '/admin/mensajes',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/mensajes': typeof AdminMensajesRoute
  '/comparativa/autocontrolpiscinas': typeof ComparativaAutocontrolpiscinasRoute
  '/comparativa/eisi-hotel': typeof ComparativaEisiHotelRoute
  '/comparativa/evisane': typeof ComparativaEvisaneRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/mensajes': typeof AdminMensajesRoute
  '/comparativa/autocontrolpiscinas': typeof ComparativaAutocontrolpiscinasRoute
  '/comparativa/eisi-hotel': typeof ComparativaEisiHotelRoute
  '/comparativa/evisane': typeof ComparativaEvisaneRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/mensajes': typeof AdminMensajesRoute
  '/comparativa/autocontrolpiscinas': typeof ComparativaAutocontrolpiscinasRoute
  '/comparativa/eisi-hotel': typeof ComparativaEisiHotelRoute
  '/comparativa/evisane': typeof ComparativaEvisaneRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contacto'
    | '/sitemap.xml'
    | '/admin/mensajes'
    | '/comparativa/autocontrolpiscinas'
    | '/comparativa/eisi-hotel'
    | '/comparativa/evisane'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contacto'
    | '/sitemap.xml'
    | '/admin/mensajes'
    | '/comparativa/autocontrolpiscinas'
    | '/comparativa/eisi-hotel'
    | '/comparativa/evisane'
  id:
    | '__root__'
    | '/'
    | '/contacto'
    | '/sitemap.xml'
    | '/admin/mensajes'
    | '/comparativa/autocontrolpiscinas'
    | '/comparativa/eisi-hotel'
    | '/comparativa/evisane'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactoRoute: typeof ContactoRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AdminMensajesRoute: typeof AdminMensajesRoute
  ComparativaAutocontrolpiscinasRoute: typeof ComparativaAutocontrolpiscinasRoute
  ComparativaEisiHotelRoute: typeof ComparativaEisiHotelRoute
  ComparativaEvisaneRoute: typeof ComparativaEvisaneRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparativa/evisane': {
      id: '/comparativa/evisane'
      path: '/comparativa/evisane'
      fullPath: '/comparativa/evisane'
      preLoaderRoute: typeof ComparativaEvisaneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparativa/eisi-hotel': {
      id: '/comparativa/eisi-hotel'
      path: '/comparativa/eisi-hotel'
      fullPath: '/comparativa/eisi-hotel'
      preLoaderRoute: typeof ComparativaEisiHotelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparativa/autocontrolpiscinas': {
      id: '/comparativa/autocontrolpiscinas'
      path: '/comparativa/autocontrolpiscinas'
      fullPath: '/comparativa/autocontrolpiscinas'
      preLoaderRoute: typeof ComparativaAutocontrolpiscinasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/mensajes': {
      id: '/admin/mensajes'
      path: '/admin/mensajes'
      fullPath: '/admin/mensajes'
      preLoaderRoute: typeof AdminMensajesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactoRoute: ContactoRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AdminMensajesRoute: AdminMensajesRoute,
  ComparativaAutocontrolpiscinasRoute: ComparativaAutocontrolpiscinasRoute,
  ComparativaEisiHotelRoute: ComparativaEisiHotelRoute,
  ComparativaEvisaneRoute: ComparativaEvisaneRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
